name: ironsource_mediation
description: IronSource ad mediation Flutter plugin. Monetize apps with rewarded video, interstitial, banner, and native ads.
version: 3.1.1
homepage: https://is.com
documentation: https://developers.is.com/ironsource-mobile/flutter/flutter-plugin/
repository: https://github.com/ironsource-mobile/Flutter-SDK

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0
  build_runner: ^2.1.11
  build_test: ^2.1.4
  flutter_lints: ^1.0.0

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.ironSource.ironsource_mediation
        pluginClass: IronSourceMediationPlugin
      ios:
        pluginClass: IronSourceMediationPlugin
